#include "sizes.h"

#define U_STACK_SIZE (16*K)
#define USER_STACK_VMA CANON( (1L<<48) - U_STACK_SIZE )
#define USER_STACK_START ((uintptr_t)STACK(USER_STACK_VMA, U_STACK_SIZE))
#define USER_TEXT_VMA 0x1000000
#define USER_TEXT_SIZE (16*K)
#define NUM_USER_PROGS 2
#define USER_VIDEO (USER_TEXT_VMA + USER_TEXT_SIZE*NUM_USER_PROGS)
#define USER_VIDEO_SIZE (8*K)
#define USER_HEAP (USER_VIDEO + USER_VIDEO_SIZE)

#define TEST_PROG_PMA 0x20000
